### PR TITLE
src/components: show team size and members count in FormFieldSelectTable component

### PR DESCRIPTION
**Pull request by maceksimon**
Show team size and members count in `FormFieldSelectTable` component.

* In composable `useApiGetTeams`, add `members` (source API) and `maxMembers` (source config) fields.
* Update template to show colored icons and members count for each team.
* Update test fixtures, to test option with full team.
* Add component test for correct displaying of team info.

### CODE REVIEW

**Comment by tmszi** [comment]
Could @maceksimon resolve conflicts please?

**Comment by maceksimon** [comment]
> Could @maceksimon resolve conflicts please?

These have been resolved.

**Comment by tmszi** [comment]
Could @maceksimon resolve conflicts again, and refactor code to use max. team memebers value from the store var (merged PR #801) please?

**Comment by maceksimon** [comment]
> Could @maceksimon resolve conflicts again, and refactor code to use max. team memebers value from the store var (merged PR #801) please?

Updated (I left the config variable as a default option in case the store var is not available).

**Pull request merged**
