### PR TITLE
src/components/homepage: update styling of BannerRoutes component based on design

### PR DESCRIPTION
**Pull request by maceksimon**
Update component `BannerRoutes` based on design.

* Add banner image.
* Update component colors.
* Add button link to routes/list page.
* Update responsive layout.
* Refactor component variants into an enum.
* Remove obsolete styles.
* Refactor tests into common coreTests function.
* Add a new command to test stacked layout.

Screenshot 2024-08-23 at 09 12 46

### CODE REVIEW

**Comment by tmszi** [comment]
@maceksimon  if original image format is SVG format, you can use it. You don't need extra PNG image format no?

**Comment by maceksimon** [comment]
> @maceksimon if original image format is SVG format, you can use it. You don't need extra PNG image format no?

Screenshot 2024-08-26 at 14 56 43

Image is in fact PNG in the original design - export as SVG will merely encode the image data into the SVG `image` tag.

**Comment by tmszi** [comment]
> Image is in fact PNG in the original design - export as SVG will merely encode the image data into the SVG `image` tag.

If you look at this image it is vector type, I don't understand why designer not use vector SVG format for exporting by default.

**Comment by maceksimon** [comment]
> If you look at this image it is vector type, I don't understand why designer not use vector SVG format for exporting by default.

I asked in Slack chat for better export.

**Comment by maceksimon** [comment]
@tmszi I replaced the image with SVG version.

**Review by tmszi — APPROVED** [review]

**Pull request merged**
