### PR TITLE
src/components: update component ListCardFollow based on graphic design

### PR DESCRIPTION
**Pull request by maceksimon**
Update component ListCardFollow based on graphic design:

* Remove top padding and negative margin
* Add arrow icon
* Put avatar, text and icon into one line
* Stack title + cards

### CODE REVIEW

**Comment by tmszi** [comment]
I found bug which related with partially not showing pointer cursor on the last card element only if mobile view is active. 
Horizontally bottom 1/2 of  last card element is not clickable (pointer is not showing), because is covered by hidden footer element (check this with web console inspector tool).

card_follow_without_pointer

You can fix it in the new PR.

**Comment by tmszi** [comment]
Could you explain why you use this icon dir path [./public/icons/lucide.svg](https://github.com/auto-mat/ride-to-work-by-bike-frontend/pull/558/files#diff-e42deec2fa79466a10ef5bd5651b067ecb58951c85873279f1163d61c6b538f7) instead of ./src/assets/svg/ path, please?

**Comment by maceksimon** [comment]
> I found bug which related with partially not showing pointer cursor on the last card element only if mobile view is active. Horizontally bottom 1/2 of last card element is not clickable (pointer is not showing), because is covered by hidden footer element (check this with web console inspector tool).

Ok. Good point.
I think this problem should be eliminated when I update footer based on the new graphic design.

**Comment by maceksimon** [comment]
> Could you explain why you use this icon dir path [./public/icons/lucide.svg](https://github.com/auto-mat/ride-to-work-by-bike-frontend/pull/558/files#diff-e42deec2fa79466a10ef5bd5651b067ecb58951c85873279f1163d61c6b538f7) instead of ./src/assets/svg/ path, please?

The [SVG use approach](https://quasar.dev/vue-components/icon#svg-use-way) specified in docs references public folder. I like this approach, because icons are not bundled into javascript, but referenced as external resource.
Also, it preserves the icon SVG behaviour, so you can set color with variable e. g.: `color="primary"`. If we use the [img: approach](https://quasar.dev/vue-components/icon#image-icons) which we have discussed before, color needs to be hard-coded.
In the design, we are using mostly [Tabler icons](https://icones.js.org/collection/tabler) or [Lucide icons](https://icones.js.org/collection/lucide) so this is a suggestion to start organizing custom icons based on the icon set.
If we decide to go this way, some refactor is needed (I have previously organized some custom icons based on component).

We did use `assets` folder for SVGs, but mostly to use them as background images, e. g.: in `RegisterChallengePage`. We also had to use a workaround here with syntax:

``` 
const doneIcon = `img:${
   new URL('../assets/svg/check.svg', import.meta.url).href
}`;
```

I think all this should be unified into one approach. A separate PR is probably needed for this.

Screenshot 2024-09-07 at 11 44 14

**Comment by tmszi** [comment]
> > Could you explain why you use this icon dir path [./public/icons/lucide.svg](https://github.com/auto-mat/ride-to-work-by-bike-frontend/pull/558/files#diff-e42deec2fa79466a10ef5bd5651b067ecb58951c85873279f1163d61c6b538f7) instead of ./src/assets/svg/ path, please?
> 
> The [SVG use approach](https://quasar.dev/vue-components/icon#svg-use-way) specified in docs references public folder. I like this approach, because icons are not bundled into javascript, but referenced as external resource. Also, it preserves the icon SVG behaviour, so you can set color with variable e. g.: `color="primary"`. If we use the [img: approach](https://quasar.dev/vue-components/icon#image-icons) which we have discussed before, color needs to be hard-coded. In the design, we are using mostly [Tabler icons](https://icones.js.org/collection/tabler) or [Lucide icons](https://icones.js.org/collection/lucide) so this is a suggestion to start organizing custom icons based on the icon set. If we decide to go this way, some refactor is needed (I have previously organized some custom icons based on component).
> 
> We did use `assets` folder for SVGs, but mostly to use them as background images, e. g.: in `RegisterChallengePage`. We also had to use a workaround here with syntax such as:
> 
> ```
> const doneIcon = `img:${
>    new URL('../assets/svg/check.svg', import.meta.url).href
> }`;
> ```
> 
> I think all this should be unified into one approach. A separate PR is probably needed for this.


Small sized mages aka vector SVG, can be embedded into JS code  path is ./assets dir. Big images aka raster should be in ./public dir.

**Review by tmszi — APPROVED** [review]

**Pull request merged**
