### PR TITLE
package: Update Vue i18n to version 10.x with custom fixes for breaking changes

### PR DESCRIPTION
**Pull request by maceksimon**
Add "vue-i18n": "^10.0.0".
Fix issue with breaking change in `test/cypress/support/commands.js`.
Replace historic duplications of the command in `CountdownEvent` and `DrawerHeader` components.
Fix inconsistency between the use of `Email` label in translation strings.

### CODE REVIEW

**Comment by tmszi** [comment]
Incorporate bug fix into PR #570 please.

**Comment by maceksimon** [comment]
> Maybe it will be not working (incorporate bug fix commit into existed Mend Renovate PR), because permission settings.

Yes, I was not allowed to push to that branch. That's why I made a new one.
There is one more issue that does not seem to be related to i18n upgrade. I will test it in main. If present, I will fix it in a separate PR, if not I will try a fix here.

**Comment by maceksimon** [comment]
PR #579 fixes the above issue. Once it is merged and this branch rebased, tests should pass.

**Comment by tmszi** [comment]
Changes was incorporated in original upgrade vue-i18n Mend Renovate PR #570.

**Pull request closed without merging**
